service: express-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    JWT_SECRET: abcd1234  # Environment variable for your Lambda function

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /{proxy+}
          method: any
          cors: true

package:
  exclude:
    - node_modules/aws-sdk/**

plugins:
  - serverless-offline
